#!/bin/bash

###
### Copy to your path and make executable
###

STRONG_URL="https://www.dinopass.com/password/strong"
SIMPLE_URL="https://www.dinopass.com/password/simple"

if [ "$1" == "strong" ]; then
    curl $STRONG_URL
    echo ""
    echo ""
elif [ "$1" == "simple" ]; then
    curl $SIMPLE_URL
    echo ""
    echo ""
else
    echo "Invalid command. Use 'strong' or 'simple'."
fi
