#!/bin/bash

# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as sudo. Please try again with sudo"
    exit 1
fi

# Flush DNS cache
dscacheutil -flushcache
killall -HUP mDNSResponder

echo "DNS cache flushed, probably..."
